replicaCount: 2

image:
  repository: <account_id>.dkr.ecr.us-west-2.amazonaws.com/lesson-5-ecr
  tag: "latest"
  pullPolicy: ifNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaler:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

env:
  - name: DJANGO_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: django-secrets
        key: DJANGO_SECRET_KEY
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: django-secrets
        key: DATABASE_URL
