pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: jenkins-kaniko
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.16.0-debug
      imagePullPolicy: Always
      command:
        - sleep
      args:
        - 99d
      volumeMounts:               
        - name: ecr-secret
          mountPath: /kaniko/.docker
  volumes:                       
    - name: ecr-secret
      secret:
        secretName: ecr-docker-config
"""
    }
  }

  environment {
    ECR_REGISTRY = "397114334021.dkr.ecr.us-west-2.amazonaws.com"
    IMAGE_NAME   = "app"
    IMAGE_TAG    = "$(git rev-parse --short HEAD)"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build & Push Docker Image') {
      steps {
        container('kaniko') {
          sh '''
            /kaniko/executor \
              --context `pwd` \
              --dockerfile `pwd`/Dockerfile \
              --destination=$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG \
              --cache=true
          '''
        }
      }
    }
  }
}
