config:
  region: us-west-2
  metrics:
    - aws_namespace: AWS/RDS
      aws_metric_name: CPUUtilization
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]
    - aws_namespace: AWS/RDS
      aws_metric_name: FreeStorageSpace
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]
