apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-django-config
data:
  DJANGO_SECRET_KEY: {{ .Values.env.DJANGO_SECRET_KEY | quote }}
  DJANGO_DEBUG: {{ .Values.env.DJANGO_DEBUG | quote }}
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}